version: '3.7'

services:
  nginx:
    container_name: ubuntuginx
    image: ubuntuginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /var/www/html:/usr/share/nginx/html
      - .:/app
    restart: always